using System.Text.Json.Serialization;

[JsonSourceGenerationOptions(
    GenerationMode = JsonSourceGenerationMode.Metadata,
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull)]
[JsonSerializable(typeof(ErrorResult))]
[JsonSerializable(typeof(StatusResult))]
[JsonSerializable(typeof(WorkerRoutesResult))]
[JsonSerializable(typeof(string))]
[JsonSerializable(typeof(List<string>), TypeInfoPropertyName = "ListString")]
[JsonSerializable(typeof(AgentRuntimeInitializeResult))]
[JsonSerializable(typeof(AgentRuntimeCapabilityResult))]
[JsonSerializable(typeof(AgentRuntimeRunResult))]
[JsonSerializable(typeof(AgentRuntimeCancelResult))]
[JsonSerializable(typeof(AgentRuntimeStopResult))]
[JsonSerializable(typeof(AgentRuntimeAppendMessagesResult))]
[JsonSerializable(typeof(AgentRuntimeContextCompressionResponse))]
[JsonSerializable(typeof(AgentRuntimeContextCompressionResult))]
[JsonSerializable(typeof(AgentRuntimeReverseResponseResult))]
[JsonSerializable(typeof(AgentRuntimeReverseRequestEnvelope))]
[JsonSerializable(typeof(AgentRuntimeApprovalRequest))]
[JsonSerializable(typeof(AgentRuntimeActiveRun))]
[JsonSerializable(typeof(AgentRuntimeStreamEnvelope))]
[JsonSerializable(typeof(AgentRuntimeStreamEvent))]
[JsonSerializable(typeof(AgentRuntimeStreamEvent[]))]
[JsonSerializable(typeof(AgentRuntimeToolUseBlock))]
[JsonSerializable(typeof(AgentRuntimeToolResult))]
[JsonSerializable(typeof(AgentRuntimeToolResult[]))]
[JsonSerializable(typeof(AgentRuntimeToolCallState))]
[JsonSerializable(typeof(AgentRuntimeImageError))]
[JsonSerializable(typeof(AgentRuntimeRequestDebugInfo))]
[JsonSerializable(typeof(AgentRuntimeTokenUsage))]
[JsonSerializable(typeof(AgentRuntimeRequestTiming))]
[JsonSerializable(typeof(NativeOpenAIImagesResult))]
[JsonSerializable(typeof(NativeGeneratedImage))]
[JsonSerializable(typeof(NativeGeneratedImage[]))]
[JsonSerializable(typeof(NativeOpenAIAudioTranscriptionResult))]
[JsonSerializable(typeof(NativeExtensionToolExecutionResult))]
[JsonSerializable(typeof(Dictionary<string, string>))]
[JsonSerializable(typeof(ImageReadResult))]
[JsonSerializable(typeof(BinaryReadResult))]
[JsonSerializable(typeof(DocumentReadResult))]
[JsonSerializable(typeof(FileMutationResult))]
[JsonSerializable(typeof(FileWriteResult))]
[JsonSerializable(typeof(FileStatResult))]
[JsonSerializable(typeof(ReadTextLinesResult))]
[JsonSerializable(typeof(List<ListDirItem>), TypeInfoPropertyName = "ListListDirItem")]
[JsonSerializable(typeof(List<SearchFileItem>), TypeInfoPropertyName = "ListSearchFileItem")]
[JsonSerializable(typeof(GlobToolResult))]
[JsonSerializable(typeof(GrepToolResult))]
[JsonSerializable(typeof(GitExecNativeResult))]
[JsonSerializable(typeof(List<GitRepositorySummary>), TypeInfoPropertyName = "ListGitRepositorySummary")]
[JsonSerializable(typeof(NativeGitStatusDetailedResult))]
[JsonSerializable(typeof(NativeGitQueryResult))]
[JsonSerializable(typeof(DbInitializeResult))]
[JsonSerializable(typeof(SessionResetResult))]
[JsonSerializable(typeof(SessionStatusResult))]
[JsonSerializable(typeof(SessionRow))]
[JsonSerializable(typeof(List<SessionRow>), TypeInfoPropertyName = "ListSessionRow")]
[JsonSerializable(typeof(SessionFindResult))]
[JsonSerializable(typeof(SessionMutationResult))]
[JsonSerializable(typeof(SessionClearAllResult))]
[JsonSerializable(typeof(ProjectRow))]
[JsonSerializable(typeof(List<ProjectRow>), TypeInfoPropertyName = "ListProjectRow")]
[JsonSerializable(typeof(ProjectFindResult))]
[JsonSerializable(typeof(ProjectDeleteResult))]
[JsonSerializable(typeof(PlanRow))]
[JsonSerializable(typeof(List<PlanRow>), TypeInfoPropertyName = "ListPlanRow")]
[JsonSerializable(typeof(PlanFindResult))]
[JsonSerializable(typeof(PlanMutationResult))]
[JsonSerializable(typeof(TaskRow))]
[JsonSerializable(typeof(List<TaskRow>), TypeInfoPropertyName = "ListTaskRow")]
[JsonSerializable(typeof(TaskFindResult))]
[JsonSerializable(typeof(TaskMutationResult))]
[JsonSerializable(typeof(StoredFileSnapshot))]
[JsonSerializable(typeof(StoredTrackedFileChange))]
[JsonSerializable(typeof(StoredRunChangeSet))]
[JsonSerializable(typeof(List<StoredRunChangeSet>), TypeInfoPropertyName = "ListStoredRunChangeSet")]
[JsonSerializable(typeof(AgentChangeSetFindResult))]
[JsonSerializable(typeof(AgentChangeMutationResult))]
[JsonSerializable(typeof(AgentChangeDeleteResult))]
[JsonSerializable(typeof(AgentChangeHydratedListResult))]
[JsonSerializable(typeof(AgentChangeHydratedGetResult))]
[JsonSerializable(typeof(AgentChangeDiffResult))]
[JsonSerializable(typeof(AgentChangeRollbackResult))]
[JsonSerializable(typeof(ShellExecResult))]
[JsonSerializable(typeof(ShellExecutionTiming))]
[JsonSerializable(typeof(ShellAbortResult))]
[JsonSerializable(typeof(ShellStartedEvent))]
[JsonSerializable(typeof(ShellOutputEvent))]
[JsonSerializable(typeof(TerminalCreateResult))]
[JsonSerializable(typeof(TerminalMutationResult))]
[JsonSerializable(typeof(TerminalSnapshotResult))]
[JsonSerializable(typeof(TerminalSessionRecord))]
[JsonSerializable(typeof(List<TerminalSessionRecord>), TypeInfoPropertyName = "ListTerminalSessionRecord")]
[JsonSerializable(typeof(TerminalOutputChunk))]
[JsonSerializable(typeof(TerminalOutputEvent))]
[JsonSerializable(typeof(TerminalExitEvent))]
[JsonSerializable(typeof(SshExecResult))]
[JsonSerializable(typeof(SshExecTiming))]
[JsonSerializable(typeof(SshConnectionTestResult))]
[JsonSerializable(typeof(SshFileTransferResult))]
[JsonSerializable(typeof(SshUploadProgress))]
[JsonSerializable(typeof(SshUploadProgressEvent))]
[JsonSerializable(typeof(SshTransferProgress))]
[JsonSerializable(typeof(SshTransferProgressEvent))]
[JsonSerializable(typeof(SshFileMutationResult))]
[JsonSerializable(typeof(SshFileHomeResult))]
[JsonSerializable(typeof(SshFileTextResult))]
[JsonSerializable(typeof(SshFileBinaryResult))]
[JsonSerializable(typeof(SshFileStatResult))]
[JsonSerializable(typeof(SshFileListResult))]
[JsonSerializable(typeof(SshFileListEntry))]
[JsonSerializable(typeof(List<SshFileListEntry>), TypeInfoPropertyName = "ListSshFileListEntry")]
[JsonSerializable(typeof(SshFilePathResult))]
[JsonSerializable(typeof(SshTransferScanResult))]
[JsonSerializable(typeof(SshTransferNode))]
[JsonSerializable(typeof(List<SshTransferNode>), TypeInfoPropertyName = "ListSshTransferNode")]
[JsonSerializable(typeof(SshGroupRow))]
[JsonSerializable(typeof(List<SshGroupRow>), TypeInfoPropertyName = "ListSshGroupRow")]
[JsonSerializable(typeof(SshConnectionRow))]
[JsonSerializable(typeof(List<SshConnectionRow>), TypeInfoPropertyName = "ListSshConnectionRow")]
[JsonSerializable(typeof(SshConnectionFindResult))]
[JsonSerializable(typeof(SshMutationResult))]
[JsonSerializable(typeof(DrawRunRow))]
[JsonSerializable(typeof(List<DrawRunRow>), TypeInfoPropertyName = "ListDrawRunRow")]
[JsonSerializable(typeof(DrawRunMutationResult))]
[JsonSerializable(typeof(CronJobRow))]
[JsonSerializable(typeof(List<CronJobRow>), TypeInfoPropertyName = "ListCronJobRow")]
[JsonSerializable(typeof(CronRunRow))]
[JsonSerializable(typeof(List<CronRunRow>), TypeInfoPropertyName = "ListCronRunRow")]
[JsonSerializable(typeof(CronRunMessageRow))]
[JsonSerializable(typeof(List<CronRunMessageRow>), TypeInfoPropertyName = "ListCronRunMessageRow")]
[JsonSerializable(typeof(CronRunLogRow))]
[JsonSerializable(typeof(List<CronRunLogRow>), TypeInfoPropertyName = "ListCronRunLogRow")]
[JsonSerializable(typeof(CronMutationResult))]
[JsonSerializable(typeof(CronJobFindResult))]
[JsonSerializable(typeof(CronJobListResult))]
[JsonSerializable(typeof(CronRunFindResult))]
[JsonSerializable(typeof(CronRunListResult))]
[JsonSerializable(typeof(CronRunDetailResult))]
[JsonSerializable(typeof(CronStartupLoadResult))]
[JsonSerializable(typeof(SessionGoalRow))]
[JsonSerializable(typeof(List<SessionGoalRow>), TypeInfoPropertyName = "ListSessionGoalRow")]
[JsonSerializable(typeof(SessionGoalEventRow))]
[JsonSerializable(typeof(List<SessionGoalEventRow>), TypeInfoPropertyName = "ListSessionGoalEventRow")]
[JsonSerializable(typeof(SessionGoalFindResult))]
[JsonSerializable(typeof(SessionGoalClearResult))]
[JsonSerializable(typeof(MemoryRootDescriptor))]
[JsonSerializable(typeof(List<MemoryRootDescriptor>), TypeInfoPropertyName = "ListMemoryRootDescriptor")]
[JsonSerializable(typeof(MemoryPipelineJob))]
[JsonSerializable(typeof(List<MemoryPipelineJob>), TypeInfoPropertyName = "ListMemoryPipelineJob")]
[JsonSerializable(typeof(MemoryStage1Output))]
[JsonSerializable(typeof(List<MemoryStage1Output>), TypeInfoPropertyName = "ListMemoryStage1Output")]
[JsonSerializable(typeof(MemoryRootFindResult))]
[JsonSerializable(typeof(MemoryJobFindResult))]
[JsonSerializable(typeof(MemoryClearRootResult))]
[JsonSerializable(typeof(MemoryMutationResult))]
[JsonSerializable(typeof(MemoryAutomationEntry))]
[JsonSerializable(typeof(List<MemoryAutomationEntry>), TypeInfoPropertyName = "ListMemoryAutomationEntry")]
[JsonSerializable(typeof(MemoryAutomationEntryResult))]
[JsonSerializable(typeof(MemoryAutomationRollupResult))]
[JsonSerializable(typeof(List<PluginProjectRow>), TypeInfoPropertyName = "ListPluginProjectRow")]
[JsonSerializable(typeof(List<PluginSessionRow>), TypeInfoPropertyName = "ListPluginSessionRow")]
[JsonSerializable(typeof(List<PluginSessionMessageRow>), TypeInfoPropertyName = "ListPluginSessionMessageRow")]
[JsonSerializable(typeof(PluginSessionMutationResult))]
[JsonSerializable(typeof(PluginSessionFindResult))]
[JsonSerializable(typeof(PluginRouteSessionResult))]
[JsonSerializable(typeof(List<MessageRow>), TypeInfoPropertyName = "ListMessageRow")]
[JsonSerializable(typeof(List<MessageContentMatch>), TypeInfoPropertyName = "ListMessageContentMatch")]
[JsonSerializable(typeof(MessageMutationResult))]
[JsonSerializable(typeof(MessageDeleteResult))]
[JsonSerializable(typeof(MessageCountResult))]
[JsonSerializable(typeof(MessageDeleteLastResult))]
[JsonSerializable(typeof(MessageCompactResult))]
[JsonSerializable(typeof(MessageUsageStatsResult))]
[JsonSerializable(typeof(UsageAddEventResult))]
[JsonSerializable(typeof(UsageMaintenanceResult))]
[JsonSerializable(typeof(UsageAnalyticsResult))]
[JsonSerializable(typeof(DbSyncRecordDraft))]
[JsonSerializable(typeof(List<DbSyncRecordDraft>), TypeInfoPropertyName = "ListDbSyncRecordDraft")]
[JsonSerializable(typeof(DbSyncBaselineRecordState))]
[JsonSerializable(typeof(List<DbSyncBaselineRecordState>), TypeInfoPropertyName = "ListDbSyncBaselineRecordState")]
[JsonSerializable(typeof(DbSyncTombstone))]
[JsonSerializable(typeof(List<DbSyncTombstone>), TypeInfoPropertyName = "ListDbSyncTombstone")]
[JsonSerializable(typeof(DbSyncSnapshotResult))]
[JsonSerializable(typeof(DbSyncMutationResult))]
[JsonSerializable(typeof(QqWakeupEligibilityResult))]
[JsonSerializable(typeof(QqWakeupMutationResult))]
internal sealed partial class WorkerJsonContext : JsonSerializerContext;
